name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.0-preview.8.20371.14
    - name: Install dependencies
      run: dotnet restore ./src/CompileTimeInject.sln
    - name: Build
      run: dotnet build ./src/CompileTimeInject.sln --configuration GitHub --no-restore
    - name: Test
      run: dotnet test ./src/CompileTimeInject.sln --configuration GitHub --no-restore --verbosity normal
